name: zodiac_zlw
channels:
  - pytorch
  - conda-forge
  - nvidia
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argon2-cffi-bindings=21.2.0
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=41.0.3
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - ffmpeg=4.2.2
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema-specifications=2023.7.1
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.6.1
  - jupyterlab_pygments=0.1.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libopus=1.3.1
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lxml=4.9.3
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbformat=5.9.2
  - ncurses=6.4
  - nettle=3.7.3
  - notebook-shim=0.2.2
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - traitlets=5.7.1
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - x264=1!157.20191217
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.28.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - augly==1.0.0
      - babel==2.13.0
      - bm3d==4.0.1
      - bm4d==4.2.3
      - click==8.1.7
      - coloredlogs==15.0.1
      - comm==0.1.4
      - compressai==1.2.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==2.14.6
      - debugpy==1.8.0
      - diffusers==0.21.4
      - dill==0.3.7
      - et-xmlfile==1.1.0
      - executing==2.0.0
      - filelock==3.12.4
      - flatbuffers==25.2.10
      - fonttools==4.43.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.9.2
      - ftfy==6.1.1
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - imageio==2.31.5
      - importlib-metadata==7.0.1
      - invisible-watermark==0.2.0
      - iopath==0.1.10
      - ipywidgets==7.7.5
      - isoduration==20.11.0
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jupyter-client==8.3.1
      - jupyter-core==5.3.2
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==1.1.7
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lpips==0.1.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbconvert==7.16.6
      - nest-asyncio==1.5.8
      - networkx==3.1
      - notebook==7.0.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.4.2
      - onnxruntime==1.16.2
      - opencv-python==4.8.1.78
      - openpyxl==3.1.2
      - overrides==7.4.0
      - pandas==2.1.2
      - papermill==2.5.0
      - platformdirs==3.11.0
      - portalocker==2.8.2
      - protobuf==5.29.3
      - psutil==5.9.5
      - pyarrow==13.0.0
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - python-json-logger==2.0.7
      - python-magic==0.4.27
      - pytorch-fid==0.3.0
      - pytorch-msssim==1.0.0
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - regex==2023.10.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.10.4
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scipy==1.11.1
      - send2trash==1.8.3
      - stack-data==0.6.3
      - sympy==1.12
      - tenacity==8.2.3
      - tifffile==2023.9.26
      - timm==0.9.10
      - tokenizers==0.15.2
      - tomli==2.0.1
      - torch==2.4.1
      - torch-fidelity==0.3.0
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - transformers==4.37.2
      - triton==3.0.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.12.2
      - tzdata==2023.3
      - uri-template==1.3.0
      - webcolors==1.13
      - widgetsnbextension==3.6.6
      - xxhash==3.4.1
      - yarl==1.9.2
      - zipp==3.17.0
